### ISSUE TITLE
Guide to Reporting Issues

### ISSUE THREAD

**Issue by techpaul** [Infineon/XMC-for-Arduino#100]
First of you may have an issue or mis-understanding, but in all cases please state the following to assist people to answer your questions quicker.

 A.  Which XMC board are you using
 B.  Which version of XMC-for-Arduino are you using
 C.  Which version of Arduino IDE and platform you are using
 D.  Any specific extra hardware and libraries from other suppliers
 E.  Standard libraries being used
 F.  Does this happen in an example programme or empty sketch (Arduino IDE File-> New then Cerify/Complie - Tick button top left)
G. Example ***minimal*** code or links to code that demonstrate the issue

This is not to be awkward but to stop the first 6 responses asking the above questions.

Other sources of information include the wiki here at https://github.com/Infineon/XMC-for-Arduino/wiki

Also this Wiki https://github.com/techpaul/XMC-for-Arduino/wiki

**Comment by ederjc** [comment]
Thanks @techpaul for this initiative. We have now templates for reporting issues, therefore I am closing this.
