### ISSUE TITLE
Link for 'DAVE' doesn't work anymore

### ISSUE THREAD

**Issue by tankhunter8192** [Infineon/XMC-for-Arduino#110]
the link points into an empty web page

**Comment by ArkajyotiChatterjee** [comment]
Please point me towards the page that has the link.

**Comment by techpaul** [comment]
The link on installation section (Code tab on this repo) was working just now for me so I assume fixed or site came back up.

**Comment by ArkajyotiChatterjee** [comment]
Hello techpaul and tankhunter8192,
My mistake. I updated the link and forgot to update the issue.
I will be closing this issue now.
Thanks,
Arka
