### ISSUE TITLE
V1.4 release not available

### ISSUE THREAD

**Issue by techpaul** [Infineon/XMC-for-Arduino#120]
Been checking on a few platforms the release of V1.4.0 and waiting for patches has not worked

package.json still says V1.3.0

index.json still says V1.30 as last version,

Something went wrong with the release, might need redoing as not being picked in Arduino IDE Board Manager as any version newer than V1.3.0

**Comment by techpaul** [comment]
@jaenrig-ifx @mhollfelder 

Can I suggest the following some of which I do not have access to

1.  Merge latest fixes to/from develop into master
2.  Uodate package.json to show **V1.4.1**
3.  Add necessary part to https://github.com/Infineon/Assets/releases/download/current/package_infineon_index.json
4.  Any other release steps
5.  Create new version V1.4.1 here

Class V1.4.0 as a version no longer available from IDE

**Comment by jaenrig-ifx** [comment]
Since the current version is not availalble anyway. I will delete the tag and release it again.

**Comment by techpaul** [comment]
Deleting the tag may help, but be aware V1.30 in IDE appears to be offering currently quite a lot of V1,4 files so V1,3 potentially be a bit of multi version depending on when loaded.

Please make sure the JSON files are updated.

**Comment by jaenrig-ifx** [comment]
Should be now ready. Definitively we need some release automation @mhollfelder :)

**Comment by techpaul** [comment]
Currently visible and updatable here will close later after a test

**Comment by techpaul** [comment]
Correctly picking up V1.4.0 now

**Comment by techpaul** [comment]
Correctly picking up V1.4.0 now
