### ISSUE TITLE
Cant use for xmc4700 Serial1

### ISSUE THREAD

**Issue by AlucardMode0** [Infineon/XMC-for-Arduino#136]
i cant use bluetooth (HC05) to communicate with my laptop . 
im using Arduino IDE. and release 1.40

**Comment by techpaul** [comment]
Use the develop branch for now until a new version is released, as that incorporates fixes detailed above and in the merged files to ensure these things happen correctly.

See pull request #126

**Comment by techpaul** [comment]
See also Pull request #127 that has been merged into develop branch
