### ISSUE TITLE
XMC1100 XMC 2Go I2S pin assignments

### ISSUE THREAD

**Issue by djsg** [Infineon/XMC-for-Arduino#165]
I am testing XMC 2Go with IM69D130 Shield2Go with these sample code (https://github.com/Infineon/IM69D130-Microphone-Shield2Go/tree/master/examples)
Since the microphone Shield2Go uses I2S interface, for which I can find the pin assignment; however I cannot find the corresponding pins info for XMC 2Go.

**Comment by mhollfelder** [comment]
Hi djsg,

The XMC2Go re-assigns its SPI pins to use the I2S mode for the mic.
Basically, as stated [here](https://github.com/Infineon/IM69D130-Microphone-Shield2Go/wiki), we do the following assignment:

SPI:MISO -- I2S:DATA (INPUT)
SPI:SCK -- I2S:CLK
SPI:SS -- I2S:BCLK

You can find this assignment as part of the respective I2S library as well documented here:

https://github.com/Infineon/XMC-for-Arduino/tree/master/libraries/I2S 

Thanks and best regards,

Manuel
