### ISSUE TITLE
Arduino IDE can't connect XMC_1100_2GO

### ISSUE THREAD

**Issue by hubertlxb** [Infineon/XMC-for-Arduino#175]
I follow all the procedures to configure the Arduino.
However, arduino indicate that the XMC 1100 is not in the COM.
![图片](https://user-images.githubusercontent.com/86290164/122892349-e450c680-d377-11eb-9c98-f7f26297861f.png)
In additon, the J-link driver was installed,

**Comment by techpaul** [comment]
Have you selected the correct COM port ?

COM3 seems surprisingly LOW number for a USB device..

On MY system the USB devices come up in the COM30 to COM50 range when i do

   Tools -->  Port 

I get for a XMC1000 2Go the list
COM1
COM2
COM47

**Comment by hubertlxb** [comment]
Hi Paul,

thanks for your support!
I changed the Port number, but it still doesn't work.

![捕获](https://user-images.githubusercontent.com/86290164/123021761-43115100-d407-11eb-91c6-49739435100c.PNG)
![捕获1](https://user-images.githubusercontent.com/86290164/123021764-4573ab00-d407-11eb-872a-b39c5a387b07.PNG)
![捕获2](https://user-images.githubusercontent.com/86290164/123021773-499fc880-d407-11eb-9518-6847e508fbba.PNG)
![捕获4](https://user-images.githubusercontent.com/86290164/123021783-4d334f80-d407-11eb-92ec-b73e344500b4.PNG)
![捕获5](https://user-images.githubusercontent.com/86290164/123021787-502e4000-d407-11eb-9e50-e6850f4b4cf1.PNG)

**Comment by techpaul** [comment]
This suggests that something is not connected properly or has broken connection to the XMC11002Go or on the board

I have no problems with multiple XMC2Go boards

Have you checked Wiki for 64 bit system issues?

Have you tried compiling and uploading a blank sketch?

Copy the TEXT not picture of error messages

**Comment by hubertlxb** [comment]
tried compiling and uploading a blank sketch, but the error is still there.
following you can find the TEXT message.

Infineon XMC Flasher Lite
Copyright Infineon Technologies 2017
--------------------------
Windows 10
Operating System: Windows 10

Initialisation
--------------------------
Windows 10

[Error] Infineon.DebuggerExceptions: It seems that JLink software is not installed please download from www.segger.com and install it. You can specify it by setting java property xmcFlasher.JLink.dllPath 
Error downloading https://github.com/Infineon/XMC-for-Arduino/releases/latest/download/package_infineon_index.json

**Comment by techpaul** [comment]
See Issue #104 and also

https://github.com/techpaul/XMC-for-Arduino/wiki/Windows-10-64-bit-Flasher
