### ISSUE TITLE
XMC4400 Platform2Go configuration errors

### ISSUE THREAD

**Issue by techpaul** [Infineon/XMC-for-Arduino#185]
Whilst assisting on issue #182 and preparing files for Pull Request #183, I uncovered many errors in pins_arduino.h, that needs someone to update

- Board User Manual
- Infineon Wiki page and Image
- Software tests

The details are listed on my Wiki  [XMC4400 Platform2Go X1 and X2](https://github.com/techpaul/XMC-for-Arduino/wiki/XMC4400-Platform2Go-X1-and-X2 "XMC4400 Platform2Go - Additional I/O connectors"), main pointrs are

1. Many X1 and X2 pins are duplicates of the normal Shield connectors and are available on multiple physical pins. Meaning multiple Arduino pin references 
operate the same PHYSICAL port pins
2. Many definitions of these pins minimum set of Analog, PWM or GPIO pins are suspect **TEST** in your application first.
3. Manual Figure 7 (page 12) shows ADC_3 (A7) on X2 Pin 34 (P15.3), in fact it is actually on X2 Pin 32 (P14.3)
4. Manual schematic has many omissions of signals names around X1 and X2.
5. Manual Figure 9 (page 15) shows PHYSICAL pin numbers starting at 1 on each connector instead of Arduino Pin numbers.
6. Manual Figure 9 (page 15) shows P1.9 on second digital connector pin 4, as being SPI_MOSI, where as pins_arduino.h and the
[Wiki](https://github.com/Infineon/XMC-for-Arduino/wiki/XMC4400-Platform2Go "XMC4400 Platform2Go Wiki page") digram shows PWM5 **ALSO** on this pin (Arduino pin 11).
7. pins_arduino.h has errors that PWM4 on pins 11, 27, 28, 57, and 58 are **off by one** so these will actually happen on
   27, 28, 57, 58, and potential crash or corruptions.
8. pins_arduino.h has errors that PWM8 on pins 26, 29, 30, 54, 55, 59 and 86 are in a **random order** so these will actually happen on
   55, 86, 30, 39, 26, 54 and 29.
9. Removing duplicate pin definitions in pins_arduino.h means lots of work adjusting all other references to Arduino pins in the **WHOLE FILE** and updating 
 [Infineon Wiki](https://github.com/Infineon/XMC-for-Arduino/wiki/XMC4400-Platform2Go "XMC4400 Platform2Go Wiki page"), associated images and User manual for the board.

Removing these errors requires a lot of time and testing, which I do not have and have no use for this board.

A commented version of the pins arduino.h exists in my fork at https://github.com/techpaul/XMC-for-Arduino/blob/master/variants/XMC4400/config/XMC4400_Platform2GO/pins_arduino.h

My recommendation is that as long as you only use minimal pins you will be OK, Trying to even use all functions on the Arduino Shield pins, will have problems.

**Comment by boramonideep** [comment]
The issues with the PWM have been resolved. The errors in the documentation are being reworked and will be updated accordingly. Thank you for pointing these out in this comment.
