### ISSUE TITLE
XMC4 series Analog Referenece AREF pin errors

### ISSUE THREAD

**Issue by techpaul** [Infineon/XMC-for-Arduino#199]
XMC4 series boards

- XMC4200 Platform 2Go
- XMC4400 Platform 2Go
- XMC4700 Relax Kit (all versions)

**Wik**i for XMC4400 and XMC4700 claims on pinout diagram that the AREF pin is

   P2.3 Arduino pin 14

**AREF is HARDWIRED TO POWER RAILS**

P2.3 can be Arduino pin 14, but it is on a **DIFFERENT** hardware pin most likely RJ45 as the circuit shows this as ETH-RXD1

Please do **not** copy pin out from XMC4200 or XMC4400 to any new XMC4200 wiki page.

**pins_arduino.h** for XMC4400 and 4700, claims that ARduino pin 14 is "AREF  TO DO:" it is not.

**Manual and Hardware"* for XMC4200 and XMC4400 claims R109 is fitted so AREF will give 3V3 as is required **needs physical checks** as I do not have these boards.

For **XMC4700** manual and actual hardware has **no R109** so AREF is **open circuit** where as R109 should be installed.

I will be updating my Wiki on this for hardware at least for pages
https://github.com/techpaul/XMC-for-Arduino/wiki/Analog-Functions-and-Additions
and  https://github.com/techpaul/XMC-for-Arduino/wiki/XMC4xxx-Series-Analog-pins

**Comment by boramonideep** [comment]
Thanks for bringing it to our notice. The issue has been fixed in the PRs above.
