### ISSUE TITLE
a  bug for chinese user

### ISSUE THREAD

**Issue by Stephenandy** [Infineon/XMC-for-Arduino#201]
I got an error when loading xmc with arduino, can you see what's going on
![picture1](https://user-images.githubusercontent.com/99775365/188465651-9c671b9e-825a-4b9e-ab47-ea7b5b12a320.jpg)
@PabloPL

**Comment by techpaul** [comment]
See Readme.md (first page of code section above)

You are using an OLD URL

In Arduino preferences use the URL

https://github.com/Infineon/Assets/releases/download/current/package_infineon_index.json

**Comment by techpaul** [comment]
The URL should be 

https://github.com/Infineon/XMC-for-Arduino/releases/latest/download/package_infineon_index.json

Your's ends in ".jsonn" a typo

**Comment by PabloPL** [comment]
By the way @Stephenandy - i'm not connected in any way with this repo/Infineon/etc - i just did tried to use this library some time ago, found a bug and reported it here.

**Comment by techpaul** [comment]
@PabloPL  do you mean #173 or #179

The first #173 was fixed a year ago

The second #179  is new and I p[ersonally do not have resources to verify the issue and analyse the data for that host

**Comment by Stephenandy** [comment]
Um, in fact, I tried both of these URLs, re-downloaded the latest version of arduino, and used VPN, but it doesn't seem to work. I really can't find any other reason, so I came to help
![error](https://user-images.githubusercontent.com/99775365/188527658-bacff041-eecc-4038-a47d-06455911c8ba.jpg)

**Comment by PabloPL** [comment]
> @PabloPL do you mean #173 or #179
> 
> The first #173 was fixed a year ago
> 
> The second #179 is new and I p[ersonally do not have resources to verify the issue and analyse the data for that host

My message was to @Stephenandy - he did created this bug report and tagged me. I just wanted to say that i'm not a owner or maintainer of current repo/don't use it and sadly don't have time to check it that issue.

**Comment by techpaul** [comment]
The URL in the error details ends in a double 'n' If on the Preferences page  the URL ends in a single 'n', the issue is with the Arduino IDE and a localistion error for Chinese.

The URL as published is accessible (try using the URL on its own in a web browser, which should return a text file to view in the browser. Even clicking on the link above should do this.

I suspect that as you have used VPN the problem lies in the Arduino IDE, unfortunately not maintained here.

**Comment by techpaul** [comment]
@PabloPl I also am neither a maintainer or owner or this repo.

Just a contributer

**Comment by Stephenandy** [comment]
Hi@jaenrig-ifx, thanks for you advice, but it doesn't seem to work...
![错](https://user-images.githubusercontent.com/99775365/191027966-64f0c228-6a29-4b30-93fe-57ea591e520c.jpg)
