### ISSUE TITLE
Only SPI or I2C?

### ISSUE THREAD

**Issue by timmornYE** [Infineon/XMC-for-Arduino#242]
**Have you looked for an answer?**

[Wiki](https://github.com/Infineon/XMC-for-Arduino/wiki/XMC-2Go) states "Only one out of two communication protocols can be used at the same time, e.g. either SPI or I2C."

**Question/Issue**:

Does that mean, that I can not use SPI and I2C in the same program? Or is it possible to switch somehow? e.g. reading value oder I2C and then switching to SPI to send it. 

Does this also apply to UART?

**Comment by techpaul** [comment]
YES as you have the smallest processor, there are some limitations.

The USIC channels can be configured as Serial/I2C/.SPi/IIS etc... However as that board only has TWO channels on one USIC, one is reserved for serial, and the other is EITHER SPI or I2C.

There is in the libraries there are end() methods to release the SPI or I2C. I would not like to guarantee how sucessfully that will fit with YOUR APPLICATION.

Serial.end() ends but does NOT release the channel for other use.


If multiple I2C and SPI permananetly needed XMC1400 board or higher iwould be better fit.
