### ISSUE TITLE
Some details and documentation corrections

### ISSUE THREAD

**Issue by techpaul** [Infineon/XMC-for-Arduino#28]
Collection of notes I have collected

The XMC1100 Boot Kit pin out diagram is wrong and has been raised as issues in [https://github.com/Infineon/Assets/issues/2](url) and [https://github.com/Infineon/Assets/issues/1](url)

Here is a text file of collection of notes from my workings, hope these are helpful
[xmc-notes.txt](https://github.com/Infineon/XMC-for-Arduino/files/1736397/xmc-notes.txt)

Some parts require some minor patches I will shortly release as a pull request.

**Comment by mhollfelder** [comment]
I fixed the issues of the documentation.

Thank you very much and best regards,

Manuel
