### ISSUE TITLE
Suggestion on wiki

### ISSUE THREAD

**Issue by techpaul** [Infineon/XMC-for-Arduino#39]
I have now created a wiki with my notes and what I am currently working on.

These notes maybe helpful to others and you might want to add link to it on your wiki

[Techpaul Wiki](https://github.com/techpaul/XMC-for-Arduino/wiki)

**Comment by techpaul** [comment]
[Techpaul Wiki](https://github.com/techpaul/XMC-for-Arduino/wiki) has just  had some major updates and reformating for more readability and details of what has been added and improved in V1.06c version there awaiting merging into new release candidate

**Comment by mhollfelder** [comment]
If okay for you, I will now merge your wiki with the existing one and copy relevant information.
Just would like to align with you before doing so - there is lot's of relevant information for all XMC users.

Best regards,

Manuel

**Comment by techpaul** [comment]
That is fine by me more will be added when I get a few moments for updates
