### ISSUE TITLE
Help with Pin definitions of I2C and SPI for XMC 2Go platform

### ISSUE THREAD

**Issue by mhanuel26** [Infineon/XMC-for-Arduino#59]
Hi, 
I am trying to find the definition pins for I2C and SPI for the XMC 2Go platform, I understand is somehow fixed in code but not sure which Pins are actually hardwired.

Can someone please let me know,

**Comment by techpaul** [comment]
It is described in two places

On the wiki page for XMC2Go https://github.com/Infineon/XMC-for-Arduino/wiki/XMC-2Go

Also in the software pins_arduino.h file

**Comment by mhanuel26** [comment]
Thank you very much,
