### ISSUE TITLE
MODBUS Library Not supported

### ISSUE THREAD

**Issue by yuvaraaj123** [Infineon/XMC-for-Arduino#7]

**Comment by mhollfelder** [comment]
Hi,

could you please provide more information?

* Which board did you use?
* Which library for MODBUS?
* A minimum example sketch that we can reproduce the problem

Thanks and best regards,

Manuel

**Comment by mhollfelder** [comment]
We have adapted a MODBUS library implementation, but we need to test it and integrate it properly.
As soon as we have done this, we will integrate it with a new release.

Best regards,

Manuel

**Comment by mhollfelder** [comment]
We got to fix a problem so that many public libraries should work now with the XMC core.
If you face issues with your implementation, please open a new issue.

Otherwise, I am happy to support you with specific error messages here on your library as well.

Best regards,

Manuel
