### ISSUE TITLE
update 1.1.2 removes XMC devices from Boardslist on Linux

### ISSUE THREAD

**Issue by odo2063** [Infineon/XMC-for-Arduino#77]
see title

**Comment by HMenger** [comment]
same on windows 10:

Es konnte keine boards.txt in C:\Users\Hubert\AppData\Local\Arduino15\packages\Infineon\hardware\arm\1.1.2 gefunden werden. Ist sie noch von einer Version vor Arduino 1.5?
Invalid version found: 5_4-2016q3

**Comment by sherylll** [comment]
Could you try VS Code + Platform IO? It works on my Ubuntu machine. However I'll check the issue with Arduino IDE when I have time.

**Comment by odo2063** [comment]
@sherylll no, i can't. I am using arduino IDE only. since i need the easiest way cause I am working with kids.

**Comment by mhoechner** [comment]
Did you remove the temporary files as described above?

**Comment by sherylll** [comment]
If this still happens with the newest release, please reopen.
