### ISSUE TITLE
XMC1100 Serial class problem

### ISSUE THREAD

**Issue by KarlArtman** [Infineon/XMC-for-Arduino#9]
I stumbled across a subtle problem in the HardwareSerial class whereby a receive character can get caught in the USIC buffer. Since we only get an interrupt on change of state and currently the HardwareSerial class only reads one character from the USIC, one character can remain queued. This tends to show itself when debugging and you hit a breakpoint, then restart the code with serial data coming in. My solution was the following code in the HardwareSerial.cpp isr:
` XMC_UART_CH_ClearStatusFlag(_XMC_UART_config->channel, (XMC_UART_CH_STATUS_FLAG_ALTERNATIVE_RECEIVE_INDICATION |
                                    XMC_UART_CH_STATUS_FLAG_RECEIVE_INDICATION));
        while(_XMC_UART_config->channel->RBUFSR & (USIC_CH_RBUFSR_RDV0_Msk | USIC_CH_RBUFSR_RDV1_Msk))
          {
            _rx_buffer->store_char(XMC_UART_CH_GetReceivedData(_XMC_UART_config->channel));
          }`

**Comment by mhollfelder** [comment]
Thanks a lot!
We are currently preparing a new release and we will integrate the fix of this bugs, too.

Best regards,

Manuel

**Comment by mhollfelder** [comment]
This issue should now be resolved with the new [release](https://github.com/Infineon/XMC-for-Arduino/releases/tag/V1.0.3) for 1.0.3.

Many thanks from our side!

Best regards,

Manuel
