### ISSUE TITLE
XMC2Go Arduino Pins 0/1

### ISSUE THREAD

**Issue by cad435** [Infineon/XMC-for-Arduino#92]
Hey,

I just noticed on XMC2Go, Arduino Pin 0 and 1 are switched.

Arduino Pin 0 is mapped to P0.7 and Arduino Pin 1 is mapped to P0.6 (Picture shows it the other way round.)
Just tested it with XMC for Arduino Version 1.2.1

greetings
cad435

**Comment by techpaul** [comment]
See pull request #93 that fixes this and improves other items for other boards and this one

I checeked through what is Pin 0 and 1 are wrong compared to pinout diagram and circuit diagram.

If that is all you need copy file from pull request for variants/XMC1100/config/XMC1100 XMC2GO/pins_arduino.h to your local copy

You may find other items in the pull request usefiul as well

**Comment by KOMsandFriends** [comment]
Thank you, @techpaul!
