### ISSUE TITLE
How to code for UART connection between XMC1100 Boot kit to ESP32

### ISSUE THREAD

**Issue by xzsfd2457** [Infineon/XMC-for-Arduino#96]

**Comment by ArkajyotiChatterjee** [comment]
Hello,
Considering that you are using Arduino/PlatformIO IDE to program, you can connect the RX/TX of XMC1100 BootKit to TX/RX of ESP32. On ESP32 end you can use Software Serial(available already). On XMC1100 end you can either use the predefined 0 & 1 Arduino Pins for UART or define your own.
The rest is pretty similar to how you would connect an Arduino Uno with ESP32 over UART.
Also please ensure this setting in your Arduino IDE :  
![image](https://user-images.githubusercontent.com/15055797/58687060-2926f080-839e-11e9-9399-9169e97cfd4b.png)

**Comment by ArkajyotiChatterjee** [comment]
Also, if possible, we would enable an example in the libraries folder of XMC-for-Arduino to take care of UART b/n XMC1100 Bootkit, XMC4700 Relax Kit & ESP32, ESP8266.
But, tell me why do you need to interface an XMC1100 Bootkit with an ESP32?

**Comment by ironstrike** [comment]
I'm trying to send some sensor data over UART from XMC1100 Bootkit to ESP8266. In  XMC 1100 Bootkit doesn't support the SoftwareSerial. Is there any way to sen the data through UART.

**Comment by xzsfd2457** [comment]
Do we need to send some sensor data from XMC1100 2GO to ESP8266  via UART ??
Give some examples, please

**Comment by ArkajyotiChatterjee** [comment]
Hello ,
Please xzsfd2457, please elaborate on what Sensors you are trying to connect. As far as I know, Infineon Sensors can be directly interfaced with ESP32. But still, please do explain your design a lit bit more for me to help you out.
Regards,
Arka

**Comment by ArkajyotiChatterjee** [comment]
Hello ironstrike,
The Software Serial library that you are installing and downloading from Github(I guess coming from Paul Stoffregen, can also be another module) does not support the XMC out of the box. You can do you own modifications for the XMC part.
Or you can use the hardware serial library for XMC1100 2GO to handle the UART comm. b/n XMC & ESP8266.
Get back in case if you have more doubts and you need clarifications.
Regards,
Arka

**Comment by techpaul** [comment]
I will rephrase the question asked before several times

      Why do you need an XMC1100 (Boot Kit or 2GO) [b]AND[/b] ESP8266 ??

What is on the XMC1100 that is not on the ESP8266 ?

What is on the ESP8266  that is not on the XMC1100 ?

If you give up the serial to the host PC you can use it to talk to other devices like ESP8266 using standard Serial.write/.print

If you look through closed issues there is a how to add a second serial to XMC100 2GO

The way this is phrased sounds like an education project or classwork

**Comment by ArkajyotiChatterjee** [comment]
Hello techpaul,
Yes, your comment makes sense. And the author is yet to throw light on the particular questions you asked.
And since there is already a closed issue on the particular topic, I would move forward to close this issue and redirect the author to the particular issue.
Thanks for pointing me to the closed issues section.
Regards,
Arka

**Comment by xzsfd2457** [comment]
Need to integrate the Infineon radar sensor data to XMC2GO and send to ESP32 via UART

**Comment by techpaul** [comment]
So you are using a Sense2Go NOT an XMC1100 2GO

So what are you using on an ESP32 or whatever board that needs this

You are giving so little information about what you are doing this sounds like Class/Course work

Give much more detail about your setup and what you are trying to do, at the moment we have nothing to go on or even know if your code is working on Sense2GO  to work on serial BEFORE connecting to anything else. As I often mentor 16 to 18 year olds on Computer Science Embedded projects, this really does come across as school work and expecting everything to be add this module and everything works by magic. You need to describe the scope of the whole issue and get things working a bit at a time and know the data from one section is working before integrating onto the next section.

**Comment by xzsfd2457** [comment]
We did the integration with a sense2GO and XMC2GO
 but we need to send a Sense2GO data to from XMC2GO to  ESP32 via UART

**Comment by ironstrike** [comment]
> Hello ironstrike,
> The Software Serial library that you are installing and downloading from Github(I guess coming from Paul Stoffregen, can also be another module) does not support the XMC out of the box. You can do you own modifications for the XMC part.
> Or you can use the hardware serial library for XMC1100 2GO to handle the UART comm. b/n XMC & ESP8266.
> Get back in case if you have more doubts and you need clarifications.
> Regards,
> Arka

Thanks for the information...I'll try as you said and if there's any further doubts I'll let you know.

**Comment by techpaul** [comment]
I will not answer anything further as you are expecting psychic answers from what sounds like student one line questions saying open ended things.

**Comment by xzsfd2457** [comment]
ok, thank you techpaul...

**Comment by ironstrike** [comment]
> Hello ironstrike,
> The Software Serial library that you are installing and downloading from Github(I guess coming from Paul Stoffregen, can also be another module) does not support the XMC out of the box. You can do you own modifications for the XMC part.
> Or you can use the hardware serial library for XMC1100 2GO to handle the UART comm. b/n XMC & ESP8266.
> Get back in case if you have more doubts and you need clarifications.
> Regards,
> Arka

Arka I tried using Hardware Serial in XMC1100 2 GO but when I tried to compile it says that there was no pin declared . I commented the SERIAL DEBUG which was in pins_arduino.h even its not working any suggestion.
![Screenshot_20190531_190105](https://user-images.githubusercontent.com/38213304/58708853-7921a980-83d6-11e9-848c-f1b7ff53a9ee.png)

**Comment by ArkajyotiChatterjee** [comment]
> > Hello ironstrike,
> > The Software Serial library that you are installing and downloading from Github(I guess coming from Paul Stoffregen, can also be another module) does not support the XMC out of the box. You can do you own modifications for the XMC part.
> > Or you can use the hardware serial library for XMC1100 2GO to handle the UART comm. b/n XMC & ESP8266.
> > Get back in case if you have more doubts and you need clarifications.
> > Regards,
> > Arka
> 
> Arka I tried using Hardware Serial in XMC1100 2 GO but when I tried to compile it says that there was no pin declared . I commented the SERIAL DEBUG which was in pins_arduino.h even its not working any suggestion.
> ![Screenshot_20190531_190105](https://user-images.githubusercontent.com/38213304/58708853-7921a980-83d6-11e9-848c-f1b7ff53a9ee.png)

Hello ironstrike,
Please check the image that I attached in the morning. You don't need to declare a Serial1 from .ino file. Just ensure the setting I mentioned. But using the setting you cant see Serial output on your PC. 
Regards,
Arka
